version: "3.9"

services:
  megasdkrestpp:
    image: ghcr.io/jaskaransm/megasdkrestpp
    container_name: megasdkrestpp
    environment:
      - APP_PORT=8069
      - APP_THREADS=1
      - LOG_FILE=/app/megasdkrestpp.txt
      - MEGA_API_KEY=
      - MEGA_THREADS=1
      - MEGA_DEBUG="false"
    volumes:
      - ./downloads:/app/downloads
    networks:
      - megasdkrestpp
    ports:
      - "8069:8069"

networks:
  megasdkrestpp:
    name: megasdkrestpp
    driver: bridge
